name = "WGPUCompute"
uuid = "494b1f74-06dd-4437-8477-4a86f2a8d703"
authors = ["arhik <arhik23@gmail.com>"]
version = "0.1.1"

[deps]
Adapt = "79e6a3ab-5dfb-504d-930d-738a2a938a0e"
CodeTracking = "da1fd8a2-8d9e-5ec2-8556-3022fb5608a2"
ExprTools = "e2ba6199-217a-4e67-a87a-7c52f15ade04"
GPUArrays = "0c68f7d7-f131-5f86-a1c3-88cf8149b2d7"
GPUCompiler = "61eb1bfa-7361-4325-ad38-22787b887f55"
GeometryBasics = "5c1252a2-5f33-56bf-86c9-59e7332b4326"
Infiltrator = "5903a43b-9cc3-4c30-8d17-598619ec4e9b"
LLVM = "929cbde3-209d-540e-8aea-75f648917ca0"
Lazy = "50d2b5c4-7a5e-59d5-8109-a42b560f39c0"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
MacroTools = "1914dd2f-81c6-5fcd-8719-6d5c9610ff09"
Reexport = "189a3867-3050-52da-a836-e630ba90ab69"
Revise = "295af30f-e4ad-537b-8983-00126c2a3abe"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
Tracy = "e689c965-62c8-4b79-b2c5-8359227902fd"
TracyProfiler_jll = "0c351ed6-8a68-550e-8b79-de6f926da83c"
WGPUCore = "53d714bf-0d76-4802-84b4-6cb75cca55f5"
WGPUNative = "c14bfd16-04f9-4c2f-a915-b355584b5509"
WGSLTypes = "8cf5275a-6167-4820-ac24-74d7d0e6cf05"

[compat]
Adapt = "^4.0"
CodeTracking = "^1.3"
ExprTools = "^0.1"
GPUArrays = "^10.0"
GPUCompiler = "^0.25"
GeometryBasics = "^0.4"
LLVM = "^6.0"
Lazy = "^0.15"
MacroTools = "^0.5"
Reexport = "^1.2"
Revise = "^3.5"
StaticArrays = "^1.8"
WGPUCore = "^0.1"
WGPUNative = "^0.1"
WGSLTypes = "^0.1"
julia = "^1.8"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
